### ISSUE TITLE
Feature Request: Show last visited date

### ISSUE THREAD

**Issue by kgrhartlage** [Acidham/chromium-hist-bookmarks#13]
I would find it extremely helpful to be able to display the last-visited date for each result. I would even like to see that information by default in the subtitle and show the URL via a modifier key instead.

Thank you for considering this and making this workflow.

**Comment by Acidham** [comment]
Good idea, thank you.

Done...https://github.com/Acidham/chromium-hist-bookmarks/releases/tag/v2.3.0
