### ISSUE TITLE
Brave Bookmarks not showing up

### ISSUE THREAD

**Issue by MyNameIsOka** [Acidham/chromium-hist-bookmarks#14]
I just started using Workflows in Alfred and tried your extension.

I noticed that the bookmarks from Brave are not showing up when querying with `bm` keyword.
Instead, the Chrome bookmarks only show up even if I set Chrome to false.

I saw that the path to the Brave bookmarks is `/Library/Application Support/ ...`.
However, in my system (Big Sur), the bookmarks and history are located in `/Users/[user]/Library/Application Support/BraveSoftware/Brave-Browser`.

Could you please give me some tips on how to make the extension work?
Please let me know if you need any additional information.

Thanks a lot!

**Comment by Acidham** [comment]
The path I am using is `/Users/[user]/Library/Application Support/BraveSoftware/Brave-Browser/Default/Bookmarks` it will be translated in code later.

**Comment by MyNameIsOka** [comment]
Thank you for your response.
I realised that since I am using profiles, the bookmarks were not found.
I manually changed the path in the .py files and now it's working as it should.

Thanks for that awesome extension!
