### ISSUE TITLE
Support for multiple chrome profiles

### ISSUE THREAD

**Issue by crixlet** [Acidham/chromium-hist-bookmarks#15]
Currently, it only searches the default profile in chrome, as far as I can tell

**Comment by Acidham** [comment]
That's expected, and I am not planning to implement search for multiple profiles

**Comment by chriszarate** [comment]
@Acidham Would you accept a PR for this feature?

**Comment by Acidham** [comment]
Sure, I wanted to implement that feature, but I am unable to find time to do it
