### ISSUE TITLE
Updater not working

### ISSUE THREAD

**Issue by notDavid** [Acidham/chromium-hist-bookmarks#17]
Hi there,

fyi i noticed the [workflow_url variable](https://github.com/Acidham/chromium-hist-bookmarks/blob/master/src/info.plist#L179=) in the updater is not pointing to something valid, it seems the url is wrong?

It seems that as a result the updater is not working.

Thanks for the workflow by the way 🙂

**Comment by Acidham** [comment]
Thank you for raising this issue! I fixed URL with v2.5.1
