### ISSUE TITLE
Not showing favicons

### ISSUE THREAD

**Issue by moritzWa** [Acidham/chromium-hist-bookmarks#20]
**Problem**: My eyes use visual imagery to lock on a search target i.e. small images help to find the correct bookmark result
**Solution**: fetch the favicons from a service like the (undocumented) `https://icons.duckduckgo.com/ip3/${baseDomain}.ico`

**Comment by Acidham** [comment]
Good idea! I added the feature, but the issue is it delays workflow execution. Therefore, I added a flag in settings to enable/disable.

**Comment by moritzWa** [comment]
Awesome, that was fast! This works for history now but somehow the favicons are not updated for the bookmark search for me (even after re-installing the workflow and re-starting alfred) 
<img width="730" alt="image" src="https://user-images.githubusercontent.com/42035131/176118468-ec40cdf6-6bbd-46ab-842b-c0dfefa64180.png">

**Comment by moritzWa** [comment]
To speed this up, it might be nice to cash the favicons or add an async job that fetches favicons for newly visited history-URLs recently created bookmarks in the background?

**Comment by Acidham** [comment]
For time being I implemented it only for history search.

Icons will be cached but not async. but it is on my todo list to fetch async.

**Comment by Acidham** [comment]
Asynchronous Cache is implemented. Search should be displayed faster now.

**Comment by moritzWa** [comment]
> For time being I implemented it only for history search.
My request was actually mostly aimed at the bookmarks so having that would be great!

**Comment by Acidham** [comment]
I am working on it.
