### ISSUE TITLE
Issue with pyenv

### ISSUE THREAD

**Issue by SoryEscobar** [Acidham/chromium-hist-bookmarks#25]
Hi, I have pyenv installed so I think is not picking the right python interpreter because the script is not working. Do you know how can fix the workflow for my particular configuration?

**Comment by Acidham** [comment]
What python version is the workflow using? Please take a look into Workflow Debugger?

I am also using pyenv and set global to python 3.9

**Comment by SoryEscobar** [comment]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/48995148/202567865-487ccea0-050c-45b7-b5ca-1fba22a2cd72.png">

<img width="327" alt="image" src="https://user-images.githubusercontent.com/48995148/202567944-aadf40f0-a35e-451d-94d3-318eef1dd106.png">

**Comment by SoryEscobar** [comment]
<img width="853" alt="image" src="https://user-images.githubusercontent.com/48995148/202568371-e96de20a-d224-4451-91a5-7da52700cd67.png">

**Comment by SoryEscobar** [comment]
<img width="306" alt="image" src="https://user-images.githubusercontent.com/48995148/202568480-2e2cff15-8321-4477-bf8e-62885621febd.png">

**Comment by SoryEscobar** [comment]
Yes, it doesn't find anything for any given search term

**Comment by Acidham** [comment]
Are there any other errors in the debug output?

**Comment by SoryEscobar** [comment]
I see no errors, just no output:
<img width="815" alt="image" src="https://user-images.githubusercontent.com/48995148/202570248-0bd1189f-cbdb-4e80-8527-9a5b8b8474e5.png">
Im wondering if the error is because of this:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/48995148/202570364-efcfa490-82d8-4cba-b1e4-44d6baca251a.png">
It looks like it is trying to query some db/file that doesn't exist or has no data, hence no results.

**Comment by SoryEscobar** [comment]
Question, what gets stored on this variable? this is py3.sh btw 
<img width="531" alt="image" src="https://user-images.githubusercontent.com/48995148/202572851-da0f48a5-245e-4afc-a555-ccb044f6e09b.png">
Im trying to replicate manually over the console

**Comment by SoryEscobar** [comment]
I see, what would I need to skip the py3.sh and execute directly? Like this:
<img width="671" alt="image" src="https://user-images.githubusercontent.com/48995148/202573367-e46340b9-dd00-4f80-96dd-8643e1ccb38e.png">

**Comment by Acidham** [comment]
that does not work because you all settings added as env variables. you could debug it in vscode with an .env file. i can provide that to you tomorrow if you wish to debug.

another thing came to my mind: does Alfred have full disk access in system preferences ?

for me it looks like permission problem and other workflows where data dir and cache dir is required would also not work. both directories have to be created on runtime by Alfred/ wf code.

**Comment by SoryEscobar** [comment]
I just validated and indeed Alfred has full access disk permission granted. Yeah if you could provide that .env file would be great thanks!

**Comment by Acidham** [comment]
Did you try to remove the py3.sh from the Alfred workflow. 
E.g., `bh` step you need `./py3.sh chrom_history.py "$1"` → `python3 chrom_history.py "$1"`

Following the .env file content in case you want to debug:
```
edge=0
brave=1
brave_beta=0
chromium=0
chrome=0
opera=0
sidekick=0
vivaldi=0
safari=0
ignored_domains=mail.google.com,mail.gmx.com
show_favicon=1
sort_recent=1
date_format=%d.%m.%Y
alfred_workflow_cache=<add_absolute_path_to_alfred_cache_dir>
url=https://www.thingiverse.com
```
