### ISSUE TITLE
Profiles Not Searched

### ISSUE THREAD

**Issue by bwt615** [Acidham/chromium-hist-bookmarks#26]
I have three edge profiles - only seems to pull from one.

**Comment by bwt615** [comment]
It would be super cool to have all three listed and launch the bookmark based on the profile. Then you’d be the true replacement for the default search.

From: Acidham ***@***.***>
Date: Tuesday, December 13, 2022 at 4:38 PM
To: Acidham/chromium-hist-bookmarks ***@***.***>
Cc: bwt615 ***@***.***>, Author ***@***.***>
Subject: Re: [Acidham/chromium-hist-bookmarks] Profiles Not Searched (Issue #26)

Yep from the default profile. you can open .py files and additional urls if required. I never tried it but I thought someone else was successful with the change.

**Comment by Avivbens** [comment]
Any update in here?

**Comment by Acidham** [comment]
I am not planning to implement profile search, but I suggested a workaround. Did you try?

**Comment by Avivbens** [comment]
![Screenshot 2023-01-05 at 14 08 35](https://user-images.githubusercontent.com/77183871/210777034-229e6700-d40c-4f4c-bd82-a78b3b58c574.png)
Just added that. 
I'm getting 
```Code 1: ERROR: Alfred Environment "chrome-default" Variable not found!```
from `Alfred3.py:290`

**Comment by Avivbens** [comment]
![Screenshot 2023-01-05 at 14 10 07](https://user-images.githubusercontent.com/77183871/210777274-ae2344cc-5b10-49a1-8cdc-fd71e3c004a2.png)

that as well
`info.plist`

**Comment by Acidham** [comment]
Yes, you need to add a checkbox to user configuration after Chromium. The reason is to enable/disable search for that browser. See my mockup  below:

<img width="961" alt="Screenshot 2023-01-05 at 15 40 25" src="https://user-images.githubusercontent.com/17712121/210806086-4c4323c5-405e-4124-9148-ae18989129b9.png">

**Comment by Avivbens** [comment]
<img width="1078" alt="Screenshot 2023-01-05 at 17 09 15" src="https://user-images.githubusercontent.com/77183871/210812569-40a7cc20-62d2-4616-9eca-a539bf4feb13.png">

Am I missing something here?

**Comment by Avivbens** [comment]
OK, I've found it
Should be without `-` (no kebab case)

**Comment by bwt615** [comment]
No plan to add multiple profiles :( ?

I think that would be a huge differentiator for this plugin! Currently nothing that does it.

I use profiles essentially because I have multiple

**Comment by Acidham** [comment]
I am not using profiles but when I am thinking of how to implement it. A profile can be any name, and this fact makes it hard to implement. This means I need to look into the directories to find out if it is a profile or not and subsequently add it. But the implementation effort would be similar to a re-write.

**Comment by Avivbens** [comment]
I'm working on a workflow that supports it. 
Let you know about it 👌

**Comment by bwt615** [comment]
Awesome good luck!!


From: Aviv Ben Shahar ***@***.***>
Date: Thursday, January 5, 2023 at 2:51 PM
To: Acidham/chromium-hist-bookmarks ***@***.***>
Cc: bwt615 ***@***.***>, Author ***@***.***>
Subject: Re: [Acidham/chromium-hist-bookmarks] Profiles Not Searched (Issue #26)

I'm working on a workflow that supports it.
Let you know about it 👌

**Comment by Avivbens** [comment]
Just published this NEW workflow. Enjoy!

(NPM Link)[https://www.npmjs.com/package/alfred-search-bookmark]
@bwt615
