### ISSUE TITLE
[FR] Add support for Arc Browser

### ISSUE THREAD

**Issue by chrismessina** [Acidham/chromium-hist-bookmarks#28]
As of v0.85, [Arc](https://arc.net/) now supports much a richer AppleScript inventory. 

<img width="1112" alt="2023-01-12 (18 29 51) Script Editor@2x" src="https://user-images.githubusercontent.com/22610/212432545-63e516f8-5b84-4077-82cb-73d35bae33c9.png">

Raycast has just added [an extension]()https://www.raycast.com/the-browser-company/arc to [support for searching History and Tabs](https://github.com/raycast/extensions/pull/4240) and so I thought it should be possible to add support to Arc to this Workflow as well.

Thanks!

**Comment by Acidham** [comment]
Thx for heads up. I requested a download slot ...

**Comment by vitorgalvao** [comment]
Looks like this can be closed. Support added [in latest release](https://github.com/Acidham/chromium-hist-bookmarks/releases/tag/v4.1.1). Will be reflected in the Gallery quite soon.
