### ISSUE TITLE
#!/usr/bin/env python3 in Alfred does not detect python3 interpreter

### ISSUE THREAD

**Issue by avielsh** [Acidham/chromium-hist-bookmarks#5]
It's probably an alfred issue, but on my machine the interpreter was not detected using the /usr/bin/env ,So had to manually use /usr/local/bin/python3 or else the script would output err 127.

I've yet to figure how to configure Alfred to detect other paths, but in terms of portability this is a workflow issue.

**Comment by Acidham** [comment]
It seems that /use/bin/env python3 is not working on some machines. I even don't know why Alfred does not allow setting up the env generally.

I started discussion on this in forum: https://www.alfredforum.com/topic/14685-alfred-uses-python-37-instead-of-382/?do=findComment&comment=75197

**Comment by avielsh** [comment]
I See
It may be worthwhile mentioning this issue in the README.md or the WF notes, until the workaround has been found because to figure this one out, one has to turn on the Alfred debugger for the script which I'm not sure is the first place one would look...

**Comment by Acidham** [comment]
I will release new version with `/usr/bin/python3` instead of `/usr/bin/env python3`.... suboptimal but it seems this way prevents issues. Thanks for the heads up!

**Comment by avielsh** [comment]
I don't think it's a good solution. I believe python3 is only shipped with OSX since Catalina. 

My OS (Mojave) does not ship with it, as well as previous OSs.

I think there's no right way to hardcode python3's path without checking for python3's existence in common paths which means wrapping the python script with some shell checking function.

**Comment by Acidham** [comment]
You are right and that's why I implemented it with env. Given Catalina is the latest macOS I would assume this is straight forward solution.

Feel free to PR shell wrapper ;)
