### ISSUE TITLE
Add &,| logic to bookmark search

### ISSUE THREAD

**Issue by avielsh** [Acidham/chromium-hist-bookmarks#7]
Currently, only **`bh`** keyword supports AND/OR operations.
`bm` could use this enhancement as well.

Also, in `ch`, searching for multiple terms separated by space shows the cumulative results of both queries, IMO the default should be an intersection operation for white space (AND filter).

**Comment by avielsh** [comment]
Please see [here](https://github.com/avielsh/chromium-hist-bookmarks/commit/63c5af14bb6bf317f78f581e7ec7e99e20487d80) for an initial working draft.

**Comment by Acidham** [comment]
@avielsh Fixed two issues that you reported but it seems working draft is a different topic, correct?

**Comment by avielsh** [comment]
Yes, Sorry, 
That commit includes two additions - Displaying the folder name in the results and a draft of the issue described.
Since it's already fixed, you can safely ignore 👍
